client-id: some_id
client-secret: some_secret
discovery-url: https://idp.dazzlingwrench.fxinnovation.com/auth/realms/fxinnovation.com
enable-default-deny: true
listen: 0.0.0.0:3000
redirection-url: https://example.com
upstream-url: https://google.com
