client-id: <CLIENT_ID>
client-secret: <CLIENT_SECRET>
discovery-url: https://keycloak.example.com/auth/realms/<REALM_NAME>
enable-default-deny: true
listen: 127.0.0.1:3000
redirection-url: http://127.0.0.1:3000
upstream-url: http://127.0.0.1:80
